// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var benchmark, doWork, log, renderLoop;
    log = function(msg, clean) {
      var html, sel;
      if (clean == null) {
        clean = false;
      }
      sel = d3.select("#console");
      if (clean) {
        sel.html("");
      }
      html = sel.html();
      return sel.html(html + msg + "\n");
    };
    doWork = function(nSeries, size, engine) {
      var data, node, t0, t1;
      if (nSeries == null) {
        nSeries = 2;
      }
      if (size == null) {
        size = 100;
      }
      if (engine == null) {
        engine = "svg";
      }
      node = document.getElementById("vis");
      node.innerHTML = '';
      data = drd.genData(nSeries, size);
      t0 = performance.now();
      drd.dual(data, engine);
      t1 = performance.now();
      return console.log(engine, nSeries, size, t1 - t0);
    };
    renderLoop = function() {
      return d3.timer(function() {
        return doWork();
      });
    };
    benchmark = function() {
      var engines, ns, sizes;
      ns = [1, 2, 5, 10, 20, 50];
      sizes = [10, 100, 500];
      engines = ["svg", "canvas", "hc"];
      return _.each(ns, function(num) {
        return _.each(sizes, function(s) {
          return _.each(engines, function(e) {
            return doWork(num, s, e);
          });
        });
      });

      /*
      window.onload = ->
        setTimeout ->
          t = performance.timing
          console.log e, ": ", t.loadEventEnd - t.responseEnd
        , 0
       */
    };
    d3.select("#vis").style("height", drd.height + "px").style("width", drd.width + "px");
    return benchmark();
  })();

}).call(this);
