// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var doWork, loadTimes, log, renderLoop;
    log = function(msg, clean) {
      var html, sel;
      if (clean == null) {
        clean = false;
      }
      sel = d3.select("#console");
      if (clean) {
        sel.html("");
      }
      html = sel.html();
      return sel.html(html + msg + "\n");
    };
    doWork = function(size, engine) {
      var data, node;
      if (size == null) {
        size = 100;
      }
      if (engine == null) {
        engine = "svg";
      }
      node = document.getElementById("vis");
      node.innerHTML = '';
      data = drd.genData(size);
      return drd.dual(data, engine);
    };
    renderLoop = function() {
      return d3.timer(function() {
        return doWork();
      });
    };
    loadTimes = function() {
      doWork(1000, "canvas");
      return window.onload = function() {
        return setTimeout(function() {
          var t;
          t = performance.timing;
          return console.log(t.loadEventEnd - t.responseEnd);
        }, 0);
      };
    };
    return loadTimes();
  })();

}).call(this);
